VERSION 0.7

build:
    DO ../.udcs/image+DEBIAN_SLIM_12
    DO ../.udcs/os/debian+SYS_LOCALE
    DO ../.udcs/os/debian+SYS_UPGRADE
    DO ../.udcs/os/debian+SYS_TIMEZONE
    DO ../.udcs/os/debian+SYS_PKG
    DO ../.udcs/os/debian+PKG_CI_BASE
    DO ../.udcs/os/debian+PKG_USER_UTILS

    DO ../.udcs/os/debian+LANG_PYTHON
    DO ../.udcs/os/debian+LANG_PYTHON_BUILD
    DO ../.udcs+LABEL

    DO ../.udcs/tools+INSTALL_TERRAFORM
    DO ../.udcs/tools+INSTALL_TERRAGRUNT

    ENV PATH /venv/bin/:$PATH
    RUN virtualenv /venv && \
      /venv/bin/pip install prefect>=2.12.0 httpx sh poetry click typer
      

    # Must end with a / or empty
    ARG registry_host=
    # Must end with a / or empty
    ARG registry_user=mrjk78

    SAVE IMAGE --push ${registry_host}${registry_user}ci-system:latest

all:
    BUILD --platform=linux/amd64 +build
