VERSION 0.7

build:
    DO ../.udcs/image+DEBIAN_SLIM_12
    DO ../.udcs/os/debian+SYS_LOCALE
    DO ../.udcs/os/debian+SYS_UPGRADE
    DO ../.udcs/os/debian+SYS_TIMEZONE
    DO ../.udcs/os/debian+SYS_PKG
    DO ../.udcs/os/debian+PKG_CI_BASE
    DO ../.udcs/os/debian+PKG_USER_UTILS

    DO ../.udcs/os/debian+LANG_PYTHON
    DO ../.udcs/os/debian+LANG_PYTHON_BUILD
    DO ../.udcs+LABEL

    DO ../.udcs/tools+INSTALL_TERRAFORM
    DO ../.udcs/tools+INSTALL_TERRAGRUNT

    ENV PATH /venv/bin/:$PATH
    RUN virtualenv /venv && \
      /venv/bin/pip install prefect>=2.12.0 httpx sh poetry click typer
      

    # Must end with a / or empty
    ARG REGISTRY_HOST=
    # Must end with a / or empty
    ARG REGISTRY_USER=mrjk78
    ARG IMAGE_NAME=ci-prefect-devops
    ARG IMAGE_BUILD_DAY=$(date +%y%m%d)

    IF [ "$REGISTRY_HOST" != "" ]
      SAVE IMAGE --push ${REGISTRY_HOST}/${REGISTRY_USER}/${IMAGE_NAME}:latest
      SAVE IMAGE --push ${REGISTRY_HOST}/${REGISTRY_USER}/${IMAGE_NAME}:${IMAGE_BUILD_DAY}
    ELSE IF [ "$REGISTRY_USER" != "" ]
      SAVE IMAGE --push ${REGISTRY_USER}/${IMAGE_NAME}:latest
      SAVE IMAGE --push ${REGISTRY_USER}/${IMAGE_NAME}:${IMAGE_BUILD_DAY}
    ELSE
      SAVE IMAGE --push ${IMAGE_NAME}:latest
      SAVE IMAGE --push ${IMAGE_NAME}:${IMAGE_BUILD_DAY}
    END


all:
    BUILD --platform=linux/amd64 +build
