VERSION 0.7

ALPINE_3_18:
    COMMAND
    FROM alpine:3.18.3
    # 3.18.3, 3.18, 3, latest

DEBIAN_12:
    COMMAND
    FROM debian:bookworm-20230919
    # bookworm, bookworm-20230919, 12.1, 12, latest

DEBIAN_SLIM_12:
    COMMAND
    FROM debian:bookworm-20230919-slim
    # bookworm-slim, bookworm-20230919-slim, 12.1-slim, 12-slim



UBUNTU_22_04_LTS:
    COMMAND
    FROM ubuntu:jammy-20230816
    # 22.04, jammy-20230816, jammy, latest


#### FUTURE

GOLANG:
    COMMAND
    FROM golang:1-alpine

GOLANG_DEBIAN:
    COMMAND
    FROM golang:1

GO:
    COMMAND
    DO +GOLANG

GO_DEBIAN:
    COMMAND
    DO +GOLANG_DEBIAN

RUST:
    COMMAND
    FROM rust:alpine

RUST_DEFIAN:
    COMMAND
    FROM rust

JDK8:
    COMMAND
    FROM eclipse-temurin:8-jdk

JDK8_OPENJ9:
    COMMAND
    FROM ibm-semeru-runtimes:open-8-jdk

JDK11:
    COMMAND
    FROM eclipse-temurin:11-jdk

JDK11_OPENJ9:
    COMMAND
    FROM ibm-semeru-runtimes:open-11-jdk

JDK17:
    COMMAND
    FROM eclipse-temurin:17-jdk

JDK17_OPENJ9:
    COMMAND
    FROM ibm-semeru-runtimes:open-17-jdk

NODE:
    COMMAND
    FROM node:lts-buster

NGINX:
    COMMAND
    FROM nginx:alpine

CONFLUENCE:
    COMMAND
    FROM atlassian/confluence-server:7-ubuntu

JIRA:
    COMMAND
    FROM atlassian/jira-software:8.13
