VERSION 0.7

SYS_UPGRADE:
    COMMAND
    RUN apt update \
        && apt upgrade -y \
        && apt autoremove -y \
        && apt autoclean -y \
        && rm -rf /var/lib/apt/lists/*

SYS_TIMEZONE:
    COMMAND
    ENV TZ UTC

    RUN export DEBIAN_FRONTEND=noninteractive \
        && apt install tzdata -y \
        && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
        && echo ${TZ} > /etc/timezone \
        && dpkg-reconfigure --frontend noninteractive tzdata \
        && rm -rf /var/lib/apt/lists/*

SYS_LOCALE:
    COMMAND
    ENV LANG en_US.UTF-8
    ENV LC_ALL en_US.UTF-8
    ENV LANGUAGE en_US:en

    RUN apt update \
        && apt install locales fonts-noto-cjk -y \
        && locale-gen --purge en_US.UTF-8 \
        && echo 'LANG="en_US.UTF-8"' > /etc/default/locale \
        && echo 'LANGUAGE="en_US:en"' >> /etc/default/locale \
        && rm -rf /var/lib/apt/lists/*

SYS_PKG:
    COMMAND
    RUN \
      echo 'APT::Install-Recommends "0";' >  /etc/apt/apt.conf.d/01-norecommend && \
      echo 'APT::Install-Suggests "0";' >>  /etc/apt/apt.conf.d/01-norecommend && \
      apt update \
        && apt install tzdata ca-certificates gosu wget curl unzip procps iputils-ping -y \
        && rm -rf /var/lib/apt/lists/*


PKG_CI_BASE:
    COMMAND
    RUN apt update \
        && apt install nload git jq -y \
        && rm -rf /var/lib/apt/lists/*

PKG_USER_UTILS:
    COMMAND
    RUN apt update \
        && apt install vim htop iftop iotop git jq -y \
        && rm -rf /var/lib/apt/lists/*


PKG_BUILD_BASE:
    COMMAND
    RUN apt update \
        && apt install build-essential -y \
        && rm -rf /var/lib/apt/lists/*
        

LANG_PYTHON:
    COMMAND
    RUN apt update \
        && apt install python3 python3-pip -y \
        && rm -rf /var/lib/apt/lists/* \
        && update-alternatives --install /usr/bin/python python /usr/bin/python3 0

LANG_PYTHON_BUILD:
    COMMAND
    RUN apt update \
        && apt install build-essential python3-venv python3-poetry -y \
        && rm -rf /var/lib/apt/lists/*



