VERSION 0.7

build:
    DO ../.udcs/image+ALPINE_3_18
    DO ../.udcs+LABEL
    DO ../.udcs/os/alpine+UPGRADE
    DO ../.udcs/os/alpine+COMMON_PKG
    DO ../.udcs/os/alpine+PKG_NETSHOOT

    # Setting User and Home
    USER root
    WORKDIR /root
    #ENV HOSTNAME netshoot
    
    # ZSH Themes
    RUN curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
    RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    RUN git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
    COPY zshrc .zshrc
    COPY motd motd
    
    # Fix permissions for OpenShift and tshark
    RUN chmod -R g=u /root
    RUN chown root:root /usr/bin/dumpcap
    
    # Running ZSH
    CMD ["zsh"]

    # Must end with a / or empty
    ARG REGISTRY_HOST=
    # Must end with a / or empty
    ARG REGISTRY_USER=mrjk78/
    ARG IMAGE_NAME=netshoot
    ARG IMAGE_BUILD_DAY=$(date +%y%m%d)

    SAVE IMAGE --push ${REGISTRY_HOST}${REGISTRY_USER}${IMAGE_NAME}:latest
    SAVE IMAGE --push ${REGISTRY_HOST}${REGISTRY_USER}${IMAGE_NAME}:${IMAGE_BUILD_DAY}


all:
    #BUILD --platform=linux/amd64 --platform=linux/arm64 --platform=linux/arm/v7 --platform=linux/arm/v6 +build
    BUILD --platform=linux/amd64 +build
