VERSION 0.7

TIMEZONE:
    COMMAND
    ENV TZ Asia/Shanghai

    RUN apk add tzdata --no-cache \
        && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
        && echo ${TZ} > /etc/timezone

UPGRADE:
    COMMAND
    RUN apk upgrade --no-cache

COMMON_PKG:
    COMMAND
    RUN apk add bash tzdata bind-tools busybox-extras ca-certificates libc6-compat vim wget curl jq git --no-cache

INSTALL_BUILD_BASE:
    COMMAND
    RUN apk add --virtual build-dependencies alpine-sdk --no-cache

REMOVE_BUILD_BASE:
    COMMAND
    RUN apk del build-dependencies --no-cache 


# From the netshoot project: https://github.com/nicolaka/netshoot/blob/master/Dockerfile
PKG_NETSHOOT:
    COMMAND
    RUN set -ex \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
    && apk update \
    && apk upgrade \
    && apk add --no-cache \
    apache2-utils \
    bash \
    bind-tools \
    bird \
    bridge-utils \
    busybox-extras \
    conntrack-tools \
    curl \
    dhcping \
    drill \
    ethtool \
    file \
    fping \
    iftop \
    iperf \
    iperf3 \
    iproute2 \
    ipset \
    iptables \
    iptraf-ng \
    iputils \
    ipvsadm \
    httpie \
    jq \
    libc6-compat \
    liboping \
    ltrace \
    mtr \
    net-snmp-tools \
    netcat-openbsd \
    nftables \
    ngrep \
    nmap \
    nmap-nping \
    nmap-scripts \
    openssl \
    py3-pip \
    py3-setuptools \
    scapy \
    socat \
    speedtest-cli \
    openssh \
    oh-my-zsh \
    strace \
    tcpdump \
    tcptraceroute \
    tshark \
    util-linux \
    vim \
    git \
    zsh \
    websocat \
    swaks \
    perl-crypt-ssleay \
    perl-net-ssleay



